### ISSUE TITLE
On Fedora 17, gobin does nothing

### ISSUE THREAD

**Issue by rambocoder** [rjeczalik/bin#6]
I did:
```
go get -u github.com/rjeczalik/bin/cmd/gobin
```
using:
```
go version go1.4.2 linux/amd64
```
however just running ```gobin``` nothing shows up in the console. I have $GOBIN, $GOROOT and $GOPATH set.

Do I need to install packages using gobin and then they become discoverable or does it work for existing installed go packages?

**Comment by rjeczalik** [comment]
It must work out of the box. At the moment I have no Fedora box to test, can I ask you to build cmd/gobin from this branch https://github.com/rjeczalik/bin/commits/dbg and paste me back the output? (It will print paths it tried to lookup, if you're concerned about privacy go through the list and censor entries yourself or send me the output via e-mail)

```
~ $ git clone -b dbg git@github.com:rjeczalik/bin.git $GOPATH/src/github.com/rjeczalik/bin
~ $ go install -a github.com/rjeczalik/bin/...
``` 

The troubleshooting would be much faster that way...

**Comment by rambocoder** [comment]
Fedora is my work laptop, but on home laptop running Ubuntu I could not replicate the problem I had, gobin works fine on that. I will let you know on Monday what is going on the Fedora.

**Comment by rjeczalik** [comment]
@rambocoder Just FYI, I tried to reproduce the issue running gobin in Fedora under Docker and failed. It may be more related to paths / filesystem than the actual OS.

**Comment by rambocoder** [comment]
Here is the results on F17 after applying the dbg branch:
```
[rambocoder@f17]$ gobin | grep gobin
path=/home/rambocoder/gopath/bin/gobin, isreg=true, isexec=true, isbin=true
import /home/rambocoder/gopath/bin/gobin: pkg=, err=which: unable to guess an import path of the main package
````

I installed your ```gowhich``` tool and it seems to not able to recognize the import path:
```
[rambocoder@f17]$ gowhich $GOPATH/bin/gobin
which: unable to guess an import path of the main package
```
however ``gofile`` gives the following:
```
[rambocoder@f17]$ gofile $GOPATH/bin/gobin
linux_amd64
```
and just for fun
```
[rambocoder@f17]$ ldd $GOPATH/bin/gobin
	linux-vdso.so.1 =>  (0x00007fffe1df7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003d36600000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003d35a00000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d35600000)
```
The issue might be in here https://github.com/rjeczalik/which/blob/master/which.go#L100 somewhere instead. I shall add some debug statements in my copy of it and see.

**Comment by rambocoder** [comment]
Do you think it might have something to do with https://github.com/golang/go/blob/6e3cf70e684cb9a766b3cfb39a6e16a7bcf9fdc1/src/debug/gosym/symtab.go#L112 which you use https://github.com/rjeczalik/which/blob/master/which.go#L120

**Comment by rjeczalik** [comment]
@rambocoder If you're using Go at least 1.3 it should work. Lower versions are not supported. If you could prints `dirs` and `name` [here](https://github.com/rjeczalik/which/blob/master/which.go#L132) it would probably give me enough information. :)

**Comment by rambocoder** [comment]
``dirs`` is empty at that point. 

I think the reason is that my GOROOT is /home/rambocoder/go and my GOPATH is /home/rambocoder/gopath so what happens is my GOPATH string contains GOROOT string https://github.com/rjeczalik/which/blob/master/which.go#L181 and isFiltered always returns true.

On my ubuntu workstation my GOROOT is /home/rambocoder/go and my GOPATH is /home/rambocoder/gpath and that works.

**Comment by rambocoder** [comment]
Btw, you are right the the Files field https://github.com/golang/go/blob/6e3cf70e684cb9a766b3cfb39a6e16a7bcf9fdc1/src/debug/gosym/symtab.go#L112 her is not nil. The comment in Go's source code was confusing "Go 1.2 and later" which I assumed Go 1.2+, but what it means is that versions before Go 1.2 :)

**Comment by rjeczalik** [comment]
> I think the reason is that my GOROOT is /home/rambocoder/go and my GOPATH is /home/rambocoder/gopath 

@rambocoder Oh pretty obvious bug. Mind sending PR?

**Comment by rambocoder** [comment]
I'm not sure how to fix it. Append a slash to the end of GOROOT and then check if the path contains it? Bu then somebody might have $GOPATH be inside of $GOROOT, such as $GOROOT/gopath/ or something like that.

**Comment by rjeczalik** [comment]
@rambocoder The simplest fix would be to add `src` subdirectory to goroot for filtering [here](https://github.com/rjeczalik/which/blob/master/which.go#L17). If someone has GOPATH inside GOROOT/src then we don't want to fix it either way ;)

```go
	...
	filtered[filepath.Join(goroot, "src")] = struct{}{}
	if err := os.Setenv("GOROOT", ""); err == nil {
		filtered[filepath.Join(runtime.GOROOT(), "src")] = struct{}{} // $GOROOT_FINAL
	...
```

**Comment by rambocoder** [comment]
@rjeczalik good solution. Solves it. Thank you. Since it would be me just copy/pasting your code, you do the commit?

**Comment by rjeczalik** [comment]
@rambocoder It's still some work, cloning, pasting, running tests and sending PR is also work and contribution that is welcomed. Even creating an issue in `which` repository so we don't lose this would be also helpful.
